import React from 'react'
import TextTransition, { presets } from 'react-text-transition'
import data from './data/data.json'
import Items from './components/List/List'
import Footer from './components/Footer/Footer'
import './App.scss'

function App() {
  const [index, setIndex] = React.useState(0)
  const TEXTS = [
    '欢迎提交你认为的优质站点或文档',
    '日常收集优质站点',
    '期待你的参与',
  ]

  React.useEffect(() => {
    const intervalId = setInterval(
      () => setIndex((index) => index + 1),
      5000 // every 3 seconds
    )
    return () => clearTimeout(intervalId)
  }, [])

  return (
    <div className="App">
      <h6 className="statistical_h6">
        <img
          src="data:image/png;base64,iV
            BORw0KGgoAAAANSUhEUgAAAF
            AAAAAoCAYAAABpYH0BAAAYhG
            lDQ1BpY2MAAHjalVlnVFNb05
            6Tc5JA6Am9ht6R3ntv0juohB
            A6IYSmgCKoKMUCKqIoKiICFq
            yADQSxoCigF2yIIFJUVFDBAs
            j3A/Te977fWt/69o/sWbOfeW
            bmmayTdbIBJDpoLFYCjh8gkZ
            nK9nGypQYFh1CJY4AAF5CABF
            I0egrLxsvLHQDg9/6fa7YfEA
            CAx5o0FisB/n+LHMlIoQMgYQ
            AQEZlCTwRAbgBgeXQWOxWAYA
            8A8hmprFQAQgwACLKDgkMACN
            kAIBi9ZO8CAMGIJbsaAATZfj
            52AIRmAA5uGo0dDcDbAQDUdH
            p0KgDvGwACmRkZywQQ/A5AsK
            TH0CIBJIwBQCMxMSkSQCISAF
            TS6dEsAIliADCO+Adn9H/wR/
            zhp9Gi/9hLfQEAAId9bAorgb
            bu/ynN/70SE9J+51ACAO4Ytr
            MPAAgCIE/jk9x8AIAbAJlkRn
            h4AgAZAPkeG7mkOwCOFJPm7L
            +Ex0nSU+xCAEAYAKcdSbN3Aw
            BJAJwjM8HDfdkfERXr6AIA/A
            C4tbGpLn7LsdsYKQ6+y5wH2U
            k+nr/tKLadzXLsGRobYBnfkR
            bvb7PM/zSG4fKb/2tmjF8gAJ
            AAUFJ6bIAHAPACoIIp8b5uSx
            hULjPGzuM3hp3m4w8ACgCoMY
            PpZLvEj4ZFsR19lvGsxJTf/a
            L5MbEuHst2eWqMn/OSPmg9ne
            bgCwCiAGgjg2nj/5uHkRLk/r
            uXSIa9w1Lv6EMG03+5X3SQlW
            rrsxw7xUrwWsZjHIwEJx8AkA
            PAxFPSfZdjMfNUtt/yjDB3Vq
            qX31KdWHgczdVrqR4sHdzBDu
            yBCmlAhQhIgjiIfTjZNAnU5R
            NHoAEbooEBmsue3xGBQAM2MI
            EGvpAJH4AJDEj5E2cLNGADA9
            KBCQt/vEufmhAFNGBDOjAgBe
            JhDNiQCG6QAAxIAzYwgPknWw
            C8ATbE/ld2OiRBAiQBG2L/F5
            8N2IH7siftNy+V7zeS4ECwJz
            gTHAmqmDhmiZlh7pglZo1ZYr
            qYMWbyu9q/8fgxfC/+Nb4PP4
            R/tiY2j/2vWlbCEKQtK8WAiH
            92jClhupgBZotZYJaYCVAxYU
            wcNDF9zBizwawwM8wAMwG75b
            rTgP0vpf7VwT80X8ZxanPiOE
            U4rTlV/h3Jq8Zr8IeFAcz/0G
            ep1og/qtr9Ofl3frt/6BwJSe
            D2byS6Db2A3kHb0E70GtoEVL
            QVbUa70Oto0z++Q2+ADdF/sv
            kAA5gQDwkQ+1/5aMs52cCAFO
            2T2m+155fPIJWxNhUAwC6JtY
            4dGx2TSrVhsRIYVBcmXUuDqq
            utqwsQFBxCXXpMffEBBAAQ4e
            6/ffQtAEZTAJw///YlfgE4Sw
            Kgrvzbp7gaQJQAUDtGT2OnL/
            kwAAA8kIAPBEEMpEEeVEATdM
            EQzMAaHMAVPMEPgmE10CEGEo
            ENGZANuZAPRbAL9sIBOAzHoB
            ZOw3logmvQBrfhPvRAH7yAIR
            iF9zAFszCHIAgR4UEoiBgigy
            gi6oguYoxYIg6IO+KDBCPhSD
            TCRNKQbGQTUoSUIgeQo0gdcg
            65jLQhnUgv8gwZRt4in5GfOB
            THjRPESeGUcCtwxjgbnBvOD7
            cKF41LxmXiNuN24MpxVbhTuE
            ZcG+4+rg83hHuPm0EB5UKFUV
            lUEzVG7VBPNASNQtnoBrQQLU
            Or0DPoFfQO+hgdQifRHxgBo2
            BUTBMzw5wxf4yOJWMbsGLsAF
            aLNWId2GNsGJvCfuF58JJ4db
            wp3gUfhI/GZ+Dz8WX4Gvwl/C
            18H34UP0sgEIQJygQjgjMhmB
            BHyCIUEw4RGgg3CL2EEcIMkU
            gUI6oTLYieRBoxlZhP3E88RW
            wlPiKOEr9zcHHIcOhyOHKEcD
            A58jjKOOo5WjgecYxzzHHycy
            pymnJ6ckZyruPcyVnNeYWzm3
            OUc44kQFImWZD8SHGkXFI56Q
            zpFmmA9IWLi0uOy4TLmyuWay
            NXOddZrrtcw1w/uMncatx23G
            Hcadw7uE9w3+B+xv2Fh4dHic
            eaJ4QnlWcHTx3PTZ5Bnu+8FF
            4tXhfeSN4c3greRt5HvB/5OP
            kU+Wz4VvNl8pXxXeDr5pvk5+
            RX4rfjp/Fv4K/gv8z/hH9GgC
            KgI+ApkChQLFAv0CkwQSaSlc
            gO5EjyZvIx8k3yCAWlyFPsKH
            TKJko15RZlVJAgqCzoIhgnWC
            R4WvCh4JQQWUhfKEBorVCF0H
            WhIWFUWEnYRThBeKfweeF+4Z
            8iUiI2IgyRApEzIo9EvolKiF
            qLMkQLRRtE+0R/ilHFHMTixU
            rEmsReimPiauLe4hnileK3xC
            clBCXMJOgShRLnJZ5L4iTVJH
            0ksySPSXZJzkhJSzlJsaT2S9
            2UmpQWlraWjpPeI90i/VaGIm
            MpEyuzR6ZV5h1ViGpDTaCWUz
            uoU7KSss6yabJHZR/Kzskpy/
            nL5ck1yL2UJ8kby0fJ75Fvl5
            9SkFFYqZCtcFLhuSKnorFijO
            I+xTuK35SUlQKVtio1KU0oiy
            q7KGcqn1QeUOFRsVJJVqlS+U
            uVoGqsGq96SLVHDadmoBajVq
            HWrY5TN1SPVT+k3quB1zDRYG
            pUaTzR5Na00UzXPKk5rCWs5a
            6Vp9Wk9XGFwoqQFSUr7qz4pW
            2gnaBdrf1Ch6zjqpOnc0Xns6
            6aLl23QvcvPR49R70cvWa9aX
            11fYZ+pf5TA4rBSoOtBu0GC4
            ZGhmzDM4ZvjRSMwo0OGj0xFj
            T2Mi42vmuCN7E1yTG5ZvLD1N
            A01fS86SczTbN4s3qzCXNlc4
            Z5tfmIhZwFzeKoxZAl1TLc8o
            jlkJWsFc2qyuq1tbx1pHWN9b
            iNqk2czSmbj7batmzbS7bf7E
            zt1tvdsEftnewL7R86kB38HQ
            44DDrKOUY7nnSccjJwynK64Y
            x3dnMucX7iIuVCd6lzmXI1cl
            3v2uHG7ebrdsDttbuaO9v9yk
            rcSteVu1cOeCh6MD2aPMHTxX
            O350svZa9kr6veBG8v7wrvMR
            8dn2yfO74U3zW+9b6zfrZ+O/
            1e+Kv4p/m3B/AFhAXUBXwLtA
            8sDRwKWhG0Puh+sHhwbHBzCD
            EkIKQmZCbUIXRv6GiYQVh+WP
            8q5VVrV3WuFl+dsPr6Gr41tD
            UXwvHhgeH14fM0T1oVbSbCJe
            JgxBTdjr6P/j7SOnJP5FuGBa
            OUMR5lEVUaNRFtEb07+m2MVU
            xZzGSsXeyB2Ok457jDcd/iPe
            NPxC8mBCY0JHIkhideZpKZ8c
            yOJOmktUm9LHVWPmso2TR5b/
            IU241dk4KkrEppThVMZaV2pa
            mkbUkbTrdMr0j/nhGQcWGtwF
            rm2q51ausK1o1nOmYez8Ky6F
            nt2bLZudnD623WH92AbIjY0J
            4jn7M5Z3Sj08baXFJufO6DPO
            280ryvmwI3XdkstXnj5pEtTl
            tO5vPms/OfbDXbengbti1228
            MCvYL9Bb8KIwvvFWkXlRXNF9
            OL723X2V6+fXFH1I6HOw13Vu
            4i7GLu6i+xKqktFSjNLB3ZvX
            J34x7qnsI9X/eu2dtZpl92eB
            9pX9q+oXL38ub9Cvt37Z8/EH
            Ogr8K2ouGg5MGCg98ORR56VG
            ldeeaw1OGiwz+PxB55etTpaG
            OVUlXZMcKx9GNj1QHVd44bH6
            +rEa8pqlk4wTwxVOtT21FnVF
            dXL1m/8yTuZNrJt6fCTvWctj
            /dfEbzzNEG4Yais3A27ey7c+
            Hn+s+7nW+/YHzhzEXFiwcvUS
            4VNiKN6xqnmmKahpqDm3svu1
            5uv2J25dJVrasnrsleq7gudH
            1nC6llc8tia2brzA3Wjcm26L
            aR9jXtL24G3fyrw7vj4S23W3
            dvO96+ecfmTutdi7vXOk07L9
            8zvtd03/B+Y5dB16UHBg8uPT
            R82Nht1N3cY9Jzpde8t+WR1a
            O2x/aPb//l8tf9Po++3n7//q
            dPwp4MPY18OvEs4dn08/Tncy
            82DuAHCl/yvywblByseqX6qm
            HIcOj6sP1w12vf1y9G6CPv36
            S8mR/dPMYzVjYuM143oTtx7a
            3j2553oe9G37Pez03mfxD4cP
            CjyseLn6w/dU0FTY1Os6cXPx
            d/Efty4qv+1/YZr5nB2cTZuW
            +F38W+1/4w/nHnZ+DP8bmMee
            J8+YLqwpVfbr8GFhMXF1k0Ng
            0AAFAAwEVFAXw+AcATDEDpAS
            CFLr3zLS8UAcABQACihbzHbU
            Y10W4sH+9IQAn3ieUcTE53ki
            oXkWuS+xFPE+8Jvhr+BoFmcj
            vlvmCP0FPhVyITou/FpsV/Si
            xI4aSJMiQqjyxZjiwvrCCqKK
            IkqiypIqVKVaOqy2koaCppKa
            /Q0NbW0dM11DPVtzJwMHQxcj
            F2NHE0dTSzM7exMLc0tdK31r
            JRspWyE7Qn2S86fHEcc3rm3O
            VyzbXWbbd7zso4jyBPBy8Db2
            UfCV9+Pw5/NAAJxAVhwZwh/K
            FiYQqrNFerrlEIl6GJRwjRKZ
            FkBiVKOFoiRi5WI84o3jEhID
            GWmZ1UyqpOPsIuTylJLU4rSC
            /M2LG2fF1tZkvWi/WwQSNnzc
            b9uS82yW1O2tK2lbBNvkC30L
            bItzhqe+aOkp21u26UPC+d2S
            OwV7PMdV9U+ab9lQcuVzw6+O
            bQzGHiEbGjalXmxzyrI46n1m
            w5UVZbW3e5/t7J56fenf7RwH
            FW5JzKeasLwReTLxU0HmpqaG
            693Hml+2rPtfvX21vOtVbcyG
            lb0256k3xzrOPyrfrbB+8U3V
            3bGXHP5b5WF2/X5INbDw92s3
            pseym9I4/OP879y7tPsR/rf/
            uk62nDs9LnqS8CBoxfir+cHx
            x81TZ0fLjgddKI/xvzUYUxnr
            HZ8b8mLr7d9y7nfcIk/QP9I+
            tT0dSl6U9frL8enaV8K/+h/v
            PhfM4v08XFf8xfF53ASvFuBC
            HCS+IFjmLOaJI9lxo3H/c8zz
            jvU76n/K8E3pA/UL4IzgotCM
            +JLIj+ElsQn5X4IvlJakx6QO
            YR9ZbsZbka+SKFBEV3JTVlTu
            V3Kp2qdWqF6rEabpqaWjxan1
            b0al/U2aebrUfX9zawNdQ1kj
            UmGy+afDQdMOs0b7Sosiy2yr
            AOt3G11bUTt8fZv3V46HjWqc
            Q5xcXP1dBNxG3O/dXKmx71ni
            VeWd5RPr6+Nn46/rIBlEBi4M
            +g98EDIV2h18MaVh1ZvXvN1v
            BsGjsilk6LDGH4RXlHe8S4xb
            rFOcebJWglyjKFkrhYONZ88n
            f2j5SFNHw6OUN+rek6v8yUrL
            Lsa+vHcrg2yuRq5lls8tgcsS
            Ujf/vWmm2tBc8LvxULbtfd4b
            2TuWt7ycnSu7vf7FksE99nUO
            61P/7AlorDB5sP9VROHP51VL
            BK9ZhFtddxek3aia215XV19V
            0nP50mn9Fr8D2bfG7n+ZMXOi
            4OXPrcRGgWu6x2xfSq67Wg61
            Etqa05N3LbNrVvuZnfsfXWtt
            uFd4rvbu/cfm/7/e1dxQ+KHh
            Z0b+3Z3Jv7aP3j9L+S+5L6WU
            9Sn2Y92/J894uqgQsvbw8+e/
            VhGF6TR+Te6IxajrmMR0wcef
            vhvcFk1oeWj7+mzKbTP5/58m
            ZGdNbtW873Cz/G5yTnfRYKf3
            Usz98BZ4OuQD9ibfitBF+iCn
            Ga4zJnPsmHS5JrkPsYTyKvCR
            +Or41/s4ArmY/cQ9kl6CnEJ/
            RAuFDEURQRbRZjisuLP5Uokr
            SU/CBVIe0s/VWmkupM/Si7R8
            5UbkB+vQJVoUVxteK8Urmyvn
            KXCkNlXnW3mrpaq7qv+phGrq
            ai5lOt4hW2K75qn9AJ1eXRbd
            Vj6cvqPzLIM9Q1HDbaaWxh/M
            GkwtTFdMbsmLm3+S+Lk5bBVk
            SrS9Z0G7LNDVuWHdWuxz7PQd
            9h3PGAk6cz3vmqS7Kruusbt0
            r3kJXCKx97lHr6eFG8+r33+6
            z2VfB953fOPzPAIZAv8HlQTX
            BKiG0od2h/2OFVMat1V8+tuR
            VeQguLUI2YpXdE7mbQovSise
            j+mPrYnDi/eI0EfMKrxCvM8q
            QMVmCyKVs6BUuZTO1La0tvyK
            hcu3NdbmZGVnx25PpVG4Jy/D
            b65HrneW/y2ey3JTh/1VbGtv
            iClMKcom3Fpdsrd9TtbNx1s6
            S3dHD3x71Ymeq+sPJd+28dmD
            uodSiicu/he0fmq3SPMaoPHO
            8+gdWa12XUN5x8f1rtTFxD/d
            lP5w0vbLzY1SjWlNDccUXmas
            611y3urdfadNpPdajfOnfH9u
            7ze2u7ZB70dG/v9Xus1Af975
            ++ef7uJbxSHF4zUj+Gn8h8Dx
            +qp+hfrGaNf/jPly8uAiz99w
            cAQDAE2LsVwN8XwKcOoPgUgP
            I6ABESgBcPgJ8J4GSdAJlpB8
            TV4s/vBwIYkIACUqAGxuAMwZ
            AAubAPGqATRmABEUUMEF8kBd
            mLNCMvcShOAxeAy8U14AZRPt
            QWzUBPo2MYFQvDKrAXeEl8OP
            44/gPBkJBLeEiUIiYSWzkoHL
            EcbZzinGmcj0h6pH2keS461w
            NuE+5aHlGeYl4cbxbvN740vl
            n+TAFEoJAsTK6mGFN6BOOEiE
            LHhR2Ex0S2iaqL9oiliouJt0
            hESnJJnpcKkUalT8uEUoWovb
            I75TzlBeQfK+xTDFWSVRpTPq
            WSomqqhqh1qpdohGoqak5pPV
            pxTbtGp1R3g16svq+BqaGMEW
            I0ZHzNZI9pnJmFOa/5gEWdZa
            qVlTWHda/NBduLdk32VxxaHG
            86dTp3u/S7DrqNu0+vnPPk8B
            L2VvIx9nX3o/tnB5QHtgRNhF
            BCbcJYq6pW94WTaDYRWfTmyG
            9RxtFZMW1xpHj/hOrEmSRnVm
            XypxTz1KK0wQz9tbvWTWcFZt
            /eYJHTkuuWN7K5IN9iGxT0Fp
            3dfnBnaYnzbnTPrbKScsYBu4
            MalXJHFKv0qz1qkmsr6u+fhg
            ajcx4Xgi/FNGVf3nv1/PVHrb
            Pt0h3Ot1PvHrn3sGuhW7N31e
            MdfTeeUp7TB04PTg5LjhiPWo
            /rvOV992Ryx8cVn9qmnT93fN
            WdOTD787v3j+M/p+dNF3J+3V
            hc/DN/MkiBKhiBIwRCHGyAPX
            ASOmAQviMURBvxQJjILuQC8g
            wHOFWcHy4Pdw73GhVG3dHNaC
            s6h1lgm7AuvCg+Ct9I4CSsJj
            QS+YkJxPscGhw7OWY4wzhvk7
            RI+7hQrmSuYW5/7ns8djwtvO
            a81/ls+O7ye/MPCiQKLJL3UL
            QoDwSZQmShZmGaCJdIs2iUmL
            DYHfF1EhoSw5L7pDylOaTbZT
            ZSbWUJsg/kyuRpCloK84pdSp
            XKySoOqhKqn9XuqR/TyNEM1T
            JboaotqsOpM6/7SW9E/4nBPc
            OrRqeMD5hsNWWbhZrbWahZ8l
            vOWD23brFpsD1nd8G+yeGqY6
            tTh/M9lx7XJ26v3MdXTnvMeX
            F4C/so+5r4rfSPDFgfeCDocv
            DzkIUwuVWuq1PXHAnvjkDohp
            FMRl3UWIxSbFzcufifiU7Msq
            SJZHP2+pTWNCzdPWPf2rFMk6
            wd2eMbHHJqc3nz1m0a3xKc37
            PNteBOkXNx1w6fnUMlObul99
            woiyrn3d9cEXmIUnn7yPoqw2
            Ofj587kVZnfpJwqu/M8bPZ58
            MuGjbyNo1cvnh103WPVtEbw+
            11Hezb5neJnf336x5s7A7rtX
            ys2CfQf/ep/7PRF5kvBQfPD/
            kNz4/UjgaP8010vts26faR/9
            OT6SNf4mYMv+G+d/+smI/+pb
            c8fxQIwA0UkAIVMARHCIJE2A
            KH4So8hwVEDnFF0pBqpB/Hhb
            PH5eLaUQ7UGz2MfsZcsRN4Tj
            wb/4rgR3hI9CD2cdA5fnCWkU
            xIo1z7ua25B3iyeKm8nXwZ/G
            r8IwKHyREUVco3wTtClcJZIq
            Gi1mLq4qISXJI4yXmpn9LzVJ
            AlypHlpRS0FC2UfJSjVTaq7l
            e7pN6rMaXFv0JXO1Bng261Xr
            f+nKGqUbBxqckjM0HzYItqy0
            /WFjbbbV/Z6zkUOQ47m7uUuX
            5291p52pPbK8H7nq+aX5H/u0
            DXoPoQztDYsDurldZsCR+NsK
            PXMNCoyOibsUpx+fETie7MBp
            ZQ8lr2UKp92pkM0bUb1r3PCs
            q+vcEw50SuWN6OzdiW7PzP20
            IKzhUuFvttP7Hj5y7fkjO7SX
            ti997ep15evP9TReDB65VKh0
            uOzFdFHus6blZzolagLrN+7J
            Tv6WsNSmd3npu9sPri7UbNpl
            3NU1e8r565TmqJam1pI7czbj
            bewm573am4O3JP9X5sV82D4W
            7xHu/eLY8uPn7dR+rXfuLzlP
            1sx/O6FzcH+l6ODU6/mh9GXh
            NHCG8IozD6c+zD+ODEg7fN76
            reb5tkflj5Uf0T8dOrqebpgs
            8hX1S/fP56bSZv1v4b4VvH95
            wfZj+mfx6fC5knzTcu0H/x/D
            q/GLy4CJASpacLAAAIty0Afn
            Bx8YsSALEUYKFkcXGuanFx4R
            gAOgBwI2HpPgkAgMAPcEQCAK
            D37Mx/3eUs3TX94z3m3zsATt
            ZpKaurxdI+0w7wP9w/3o8t57
            S9AAAAIGNIUk0AAHomAACAhA
            AA+gAAAIDoAAB1MAAA6mAAAD
            qYAAAXcJy6UTwAAAAGYktHRA
            D/AP8A/6C9p5MAAAAHdElNRQ
            fmBxUXKyCNWUHWAAAQF0lEQV
            Ro3u1aeZCcxXX/dX/HHLtapN
            WxQkJCQsIIUwgsQDYy4cahIi
            6LI7jsFBBcrjgKdrkwBJsjhc
            HBBAwmopwUcsRlTAjYHDbIUY
            CCsgGBAIEwINCFVlpppZX2nv
            mOPn754/u+0czuzEoryf+k8q
            qmdqen+3W/16/f+73XLUgSVW
            SthTEGnudhKCml4LouhBDD2h
            3HgZQSB8rLGAMAcBznz8aLJL
            TWB4WXGKrA/6fRkTxwFg3IWi
            Ddtf/LNEyB1lporet21lqjns
            FqrWGtHcJZwjoSSsWANvvMy1
            o7nBf2HLvRrMsYUzl6fy5e7t
            AGIcSw81/9G8mKn8h8npSyMo
            bWQkiJnf/5CBw3h0MuvgwQIr
            HIVLEZr3rKU0ql3RKfaq2BtR
            ZCiGH+Z29rHkmOfZHRcZzKnI
            36y3oM6i2UJKy1CIJg2AKqFY
            h098LlK9B/6eXYdcH5GPzd07
            DWAFKCqSIdx6mMUUohDEOEYQ
            StDeI4+V4qldDVtRulUglSyo
            YKbNQupRwW2EYaM1TG6rGNeN
            XlXm3Cmblnn0KhAM/zahRIEg
            QT5QkJC8BftwE5AOb3/41d5y
            9C5wXnIdi0AUJK0BgQhEktzp
            jEykhWNicRhvB9H7lcHkpplE
            rlukevURwkOeJv1WSM2buMdX
            iJejDGWgvXdaG1hlIKQgh4ng
            eSNZaTkdY6sUIQQjoor/8EO4
            4/HvlyCAoJffRsYGsHYs/H5B
            deQPNJX0K5XAKQWKR0JKR0YI
            xBEASwNpknl/NTSxCI4xhKKY
            wZMwZSCEAIOFJCAFDG1EKPVC
            SjNVDHcqthjDEGSimQyWY1kn
            FUMCbbDQBwXbfhERm2q6n/07
            3d6DznHIi334WUDljwwHweYn
            cv1OHTMP6lF2EPOxyqfwCu7w
            MA4lhBawUhJHI5H06q1Ordzy
            xV+j4ca1EoJpZCYxIfKyVQ7U
            5GoCxYZgqrp7R9oRoFZoqz1s
            LzPLiuO2qGmSDB+++h6+yz4e
            zaDeG5gNKA64JaQ518EiaueA
            nS9WC1htIaxiRzSpn4HpJpEM
            mOtpMca6Ohd3WhMGsWdj3/HJ
            rHtGDsqadDkLBCACRMWAI6ux
            Du3I6meSdBVgHmTHHGGDiOAz
            /dwP0lwYSglKqJdvWUp7VuaN
            7VTpfGQDgOSu+9ja5LL4a7aQ
            ucyZNgOnYA0yaDWzrBr16I3E
            OPQAQhfM9DLp+Dkx5jgKnlAQ
            KoicZuzkfn1X8L8eZK+K2tiN
            96B/krr0Bh9iz0vf4GnN27oD
            9eC2OB3M0/xMTrrocLAabrr1
            5rvUykkYzZRg47jUopBkHAMA
            xpraW1lsYY1qOR2q21NW1WKZ
            Jk0LmNW07/C7YD3OY4bG8qct
            O4sVwHcPM3r2KvsewfKLEUxy
            wbsl8ZDhjLEskSyUGSfTb5Hp
            EMSMYkt//Dt7kVYLvncjOQ8J
            eSWwBuOW4ugz+tIUlqram1rs
            iYyTBaGTPdDCURxzHr5bEHg+
            IwhHYcqDjG4A03ILj/frhCQJ
            LwpURkLfybfojitd+H2roVHB
            wEyiV40oGlBbSBVw6hgjJ0HC
            AcDGBjDS/vwfV9xD+7B/aDj5
            BrKoJhhEgQ+Wu/hwm3/AhusY
            g4DGFBCCnhOR6kc/BlrBtEMj
            gxmnZgD9isRu06VtDWgC0tGH
            z4QejnfwdvsIz4nXeR29kF+i
            44aQJMTx8YBJCWyGYQAKwAJJ
            NDzap2AnCkSKK31tAzp6N5yX
            0Ys/Ai6HIZRik4ngcv/RxsGR
            sq8GBUY7TWCMMoxXSA0QZSCL
            jNTSAAIwTi9Z+i/7RT4G7vgh
            RyT6YiEn8lUk3pnA8pABlrgA
            IUqCiYJGAM9OwjMG7FChRmzo
            IplWFg4bh7guDBqsaQHBYbhk
            WKkdB7vQmzdpIol4MEZkgnbU
            uzjlzilEUUg7QQBNyZR6DnxC
            /AeW4F6DqA6wAmLUA4DpgK4E
            YJ1LBCQMAmfYQEBZJ+xsCbd3
            yivMES4LnwpFcB5I1SvJFkqU
            eNoNx+4JTG5HkuoihK0jZYWE
            uI1JSklKAlLA1oLKTrwFU6OY
            4pjhNA5Xt2LCrWmB5jIQRUug
            lCCAgAYcc2BGEZVhsIYyBS+L
            Mn/UtA8n7Bsr3QMI7VmchQam
            TeWSaSWSKJtKJiYIyF63oV0C
            qEgHAdQGvYI4+GXf4y/PMWor
            hgAcxnm9G/bCmar7kGuc/NAa
            yFVyzA+j4wcQK6774bYuMmtC
            xbBuH5KN9zD8zKlSjefDOkMv
            AKOTB1QQkUAeI4BpDMm8l0MA
            uqaBSyR9te/ZtSiv39AyyVyh
            wcLLFcDhiGEaMoZlAOWBossR
            zH7O/s5JrmZna98goDkrt++z
            Q3FnPs376VAyT7jWE/yQGtWS
            bZ9R9LuXHmdA7omGWSPY8+zP
            WTWjkQlFkKQkZhyDiOK2sxxl
            Q+w2DWAcqYUV1nN1KpJ9vBoe
            3VY1zXxZgxzSgU8pW0DCCsTY
            oIUiS+xuvphhcFQBzBA2A7Oh
            LwLBw45QC2pwe2uwfs64MA4L
            ZOQNjTC7t1WxKMpk2D6euHWf
            sJFIAwDBHHcSUNzfy5rJPeHa
            iMGe21GjP0eCulUj9na/o3Gl
            PdJ/GNyf+xJXQcQVgDk4QHRL
            2DoCNhQARKg9IBHBeaRKw04m
            IRNo4howi0hHfELDjFIti1A/
            l8Dp7rwnXdyno4impMPRmrKz
            +NeO2zD7TWolQqwXVd5PP5mt
            0wxtTd5WzCLN9USiEIAsRhDF
            jAMUnxAUEZIQAx0A87YSLc5h
            ZICpg0b5UpcNHawC2HkOVBUA
            g4zU0QXg5q6xaMBZKCRZWPGu
            2l0kgy2qo65ogKHApjsnKPlB
            KFQqFucGkU3Ybycl0XuVwOvu
            vB5HKIjIFQFrKvLzkKvd1gUx
            NiKRF298L1/QRHktBhAG/8uK
            R81dODQwSAceNhZ81E3NGRKF
            gpOFU5+UgVbDcNeMnGaMSxgu
            NIFIvFusYwahiTmXIGHkcLAZ
            hWdzNFZjw9z4PwBJQQ0ONa4V
            xwLuz06bAAxGmnwztsClQYQ3
            ourDVwHBeO60AojaYTT0Luxe
            XwZsyszDP13nvgt00BAHi5HC
            AEdvf0QgiBsS0tCe6UMqkhVi
            sx0WQyLs1WGmUbI9GwTERrjS
            AI4Pv+sKpMHMfDKrXAnkxECJ
            ke59pyOMmaBdcoGkA5CtG/uw
            eiqRm5Qh5FY5Ar5KFVjHIYQ6
            sYxhJNxTzcYhO6u3sQDgzCgi
            hboGNbJwa6u7Fq9Rp0dHZhyq
            QJ+P7iqzFp4oS6qVkYRujcuR
            OxUhgsldHd24+PP92I9z74AF
            +7+EKcfeqCCo7MqFEmUlFg5h
            cyTOf7fl2f1ugyyFrCdfeYeX
            tHJ1589Y94a/Ua9PX248ZrF2
            Plu+9j3br1cFwf3d3d+MKxn8
            cVl30VQgLCceF7HnZ17ca7H6
            7F6jUforevH0EYoqlYwLHHzM
            Ebq1Zj/fqNmHH4dERxjHGt42
            CVBq3FtOmH4ejZMzD7iMNhCL
            y35kN8vG4DevsGEQQBduzcAc
            /zk6qztYiiCONax6GlpQV5z8
            Wcz83GyScej1kzp0NANPTnw6
            K5tZaZ4jKLG11lhpX0bVvnDj
            z+9PNYuWo1ik1FRFGMJ5Y+jJ
            PPPQuXXbQQ48a2YMa0qZg6uQ
            0QEucs/GtccskFuOtHP8Cu7h
            4se+xJ7Orpw9RD23DopAmYcd
            gUTJnchra2SYAA5i44F3fcch
            0uWviVCliu3ti3Vr+PZ5a/hL
            EtLQiiCEuWPIDfPvkgZkybii
            iKIUQS0JqbmtDc3LRfFehhFE
            URwzCk1roCGPe1VpYBy3IY8t
            a7lvArl17F62+7i2++8x5J8q
            xFf8OLr1ycda4Bor/8r2c4c9
            4ZfPmPK6m04revu5mPPvnssD
            mydf30/qWcMHMegzCsAckqrT
            t+uHYdr73lDm5s30KSvOYHt/
            HU8y6v9LXWkFXzZ+Baa02V1g
            xHkr0RkEa2wGrGQ9uqM4xaJs
            n/53/9W/zeTf+cjk0WcNvd9/
            PwuacwjGOSZKlU4gcfreXPlz
            3GL5/3NZ5xwTf48bqNJMnBUo
            ndPT2VOaIopk4VRJJhHHPyUf
            N54+13J32GrC8rmmbt6zdtpj
            xkBh/79bOkNRwslWvWba2tKH
            7vMo6sl/1+G5Mdm22dO/HUM8
            /jO393FbQxcB0Hm7duw1HHnY
            ZFl56PE+Yeiw2bt2DjZ5thjc
            H8eXOx6Ly/xLy5x1TAaXYHkt
            zGZe6DUNrAc10seeBh3PYv92
            HD+3/AmKamhr44O9ZXLb4OH6
            3bgDdX/Kamb6kcIAxDjG8diz
            1FsQOjg/a4SBsDpFHqzPMvx5
            RDJ2P+/BPw3e/+IxYv/hbuvP
            V6+K4Pz0uimGVyj1y5RxmilO
            z77t4+HHPCmbjzxzfiissX1f
            i+oRu6/KVX8T+vvoalSx/FKa
            efgjmzZsDP+Rjf2gqjNQSI+f
            OOw1mnLmi4CftjScNMtZF5Vy
            fq1RSGIcMwIkne8pP7OOeks1
            gOApLkK6+9yeLUY/jM8hdJkl
            EU0RjTkFd2HDNX8PWrr+FfXX
            JlMk8U1V2X1prlIOC/P/Qrem
            Om8Z/uuJck+Vn7Vn66YRO37+
            xiOYwq81lrGTXgtbd1DaUDqs
            ZYa6mqfM+yXz3FyZ8/mRvbt5
            Iky+VEiTfd/lNOO+Zk6tRxW7
            vHKWttah136thJ8o1Vq3nkvN
            O5Y1d3ZXPrrSmKEj97693387
            QLv1HNaljfOFYNA8XeZK8bRH
            gAlPEzxvCG2+7iCWddxM0d25
            MdM7oyYd/gIMfPmMtfPvGbym
            7uTYByEHLeGRfy1ddXpWNqhc
            6UoNO/z/3+Jc49bSH7B0sjKo
            JMgtCm9vYRFbmvNEyB+wJj4j
            hm/8AAP93wGZf84hEuuvLv+e
            N7/61iccbsgURxnLiDny97lF
            PmfJGbtnSQJIMw5PadXXzi2e
            X8w8q3K/wz5V72ze/wlp/8rC
            Jw7boS5QRBwI7tnXxl5Ts89K
            j5fPDxX7N923au2/gZe/r6Gc
            WKYRQzVophGLJjWycff/oFXr
            n4Oj70+FN1FT3qa02yNogwzW
            HrOWqlFDzPw2tvrsLqP61FIV
            /AIS1NWDB/Hqa0taW5b/KWJe
            Nl0pRICoGHnngaL7/6OmZMnw
            pLi9bWcZg2eRK+/MUTMWVyWy
            VA3PmvD6Bz507ce/tNsJYgbe
            XS33VdRCrGLx59Eh98tBa5XB
            6bNrdj6qFtKBbykI4LpTXKpT
            KKhXwSKQWQy+fRXCxi4vhWnH
            nql3DkzBl1A0mWUGQVpuo8nn
            Uu1kcVhY0xlXx4aE7YqKSVUZ
            ZbkkSsFNyqt3fp1mVLwocff4
            LZs46A5zo1BQ3HdZNqjNbo2N
            aJtraJKORyDeez1oIQIC2kFH
            CdPWvmCFAojuPKFcXesrJ9Um
            B21am1huu6lcqFtcltrdzHBz
            1DlZztar3xSXppIED4udyIGy
            NEUjus3CcPedtX3bfRfPVk3B
            ca8XlbVtLKylCZJTS6VKr3Sn
            +0F1RRFFWs3Pf9miNUzavagg
            7klT7Td0HZXXgjGUf1vI1VlZ
            msFnhQQOcIVF1/9Dxvn5/U7S
            8xfS5XfaO4PzL+L6++RVo9kE
            bGAAAAJXRFWHRkYXRlOmNyZW
            F0ZQAyMDIyLTA3LTIxVDE1Oj
            QzOjMyKzA4OjAwFcyBrgAAAC
            V0RVh0ZGF0ZTptb2RpZnkAMj
            AyMi0wNy0yMVQxNTo0MzozMi
            swODowMGSRORIAAAASdEVYdG
            V4aWY6RXhpZk9mZnNldAAyNl
            MbomUAAAAYdEVYdGV4aWY6UG
            l4ZWxYRGltZW5zaW9uADQwM9
            nw0zwAAAAYdEVYdGV4aWY6UG
            l4ZWxZRGltZW5zaW9uADM2Of
            c/alcAAAAodEVYdGljYzpjb3
            B5cmlnaHQAQ29weXJpZ2h0IE
            FwcGxlIEluYy4sIDIwMjLktL
            +cAAAAF3RFWHRpY2M6ZGVzY3
            JpcHRpb24ARGlzcGxheRcblb
            gAAAAgdEVYdHNvZnR3YXJlAG
            h0dHBzOi8vaW1hZ2VtYWdpY2
            sub3JnvM8dnQAAABh0RVh0VG
            h1bWI6OkRvY3VtZW50OjpQYW
            dlcwAxp/+7LwAAABh0RVh0VG
            h1bWI6OkltYWdlOjpIZWlnaH
            QAMzY5U5NgfAAAABd0RVh0VG
            h1bWI6OkltYWdlOjpXaWR0aA
            A0MDNzomg8AAAAGXRFWHRUaH
            VtYjo6TWltZXR5cGUAaW1hZ2
            UvcG5nP7JWTgAAABd0RVh0VG
            h1bWI6Ok1UaW1lADE2NTgzOD
            k0MTJC8LE0AAAAE3RFWHRUaH
            VtYjo6U2l6ZQA5ODkxN0JCek
            a7cAAAAEZ0RVh0VGh1bWI6Ol
            VSSQBmaWxlOi8vL2FwcC90bX
            AvaW1hZ2VsYy9pbWd2aWV3Ml
            85XzE2NTcxNjE5NjMwMTQwND
            A5XzgwX1swXR1YfxkAAAAASU
            VORK5CYII="
          alt=""
          data-v-37dfd6fc=""
        />
        <span>
          <TextTransition springConfig={presets.slow} className="big" inline>
            {TEXTS[index % TEXTS.length]}
          </TextTransition>
        </span>
      </h6>

      <Items data={data} />
      <Footer />
    </div>
  )
}

export default App
